[package]
name = "purse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bnum = { version = "0.12.1", features = ["numtraits"] }
num = "0.4.3"
num-traits = "0.2.19"
